### ISSUE TITLE
Cocoapods supports

### ISSUE THREAD

**Issue by WezSieTato** [RougeWare/Swift-Lazy-Containers#26]
It will be great to have this library in cocoapods specs :)

**Comment by BenLeggiero** [comment]
Thank you for your suggestion, @WezSieTato! If you want to add that capability, feel free. I don't want to; I much prefer Swift Package Manager over CocoaPods, so I wouldn't know how to do that. That said, I have no opposition to supporting multiple platforms, so if you can put in a PR for that, I'll happily review it!
